import { cn } from "@/lib/utils";

/* ---------------------------------------------------------------------------
   The AI marker.

   Deliberately a symbol rather than a model name. "Claude Opus 5 · live" was
   accurate but it put a vendor's brand on the customer's product, and it made
   the model the subject when the finding is the subject.

   The badge still distinguishes live from scripted — that honesty is not
   negotiable — but it does it with a filled mark versus an outlined one, plus
   a title attribute for anyone who hovers.
------------------------------------------------------------------------- */

export function Sparkle({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 16 16" fill="none" className={cn("h-3.5 w-3.5", className)} aria-hidden>
      <path
        d="M8 1.5l1.35 3.6a3 3 0 0 0 1.75 1.75L14.5 8l-3.4 1.15a3 3 0 0 0-1.75 1.75L8 14.5l-1.35-3.6a3 3 0 0 0-1.75-1.75L1.5 8l3.4-1.15a3 3 0 0 0 1.75-1.75L8 1.5z"
        fill="currentColor"
      />
      <path d="M13.2 1.6l.45 1.2 1.2.45-1.2.45-.45 1.2-.45-1.2-1.2-.45 1.2-.45.45-1.2z" fill="currentColor" opacity="0.7" />
    </svg>
  );
}

export function AiBadge({
  live,
  className,
}: {
  /** True only when a request genuinely reached the model. */
  live: boolean;
  className?: string;
}) {
  return (
    <span
      title={live ? "Generated by AI just now" : "Pre-recorded example — no model was called"}
      className={cn(
        "inline-flex items-center gap-1.5 rounded-full border px-2.5 py-0.5 text-[11px] font-medium leading-5",
        live ? "border-accent/40 bg-accent/8 text-accent" : "border-line text-faint",
        className,
      )}
    >
      <Sparkle className={live ? "" : "opacity-50"} />
      {live ? "AI" : "Example"}
    </span>
  );
}
